name: Preliminary Release

on:
  push:
    branches:
      - 'version/*'
      - 'modules/*'

jobs:
  preliminary_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch_name::${{ github.ref }}"

      - name: Create preliminary release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_PERSONAL }}
        with:
          tag_name: ${{ steps.get_branch_name.outputs.branch_name }}
          release_name: ${{ steps.get_branch_name.outputs.branch_name }}
          body: Preliminary release based on branch ${{ github.ref }}

      - name: Upload artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./your-artifact.zip
          asset_name: your-artifact.zip
          asset_content_type: application/zip