name: Preliminary Release

on:
  push:
    branches:
      - 'version/*'
      - 'modules/*'

jobs:
  preliminary_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch_name::${{ github.ref }}"

      - name: Extract branch name
        id: extract_branch_name
        run: |
          branch_name="${{ steps.get_branch_name.outputs.branch_name }}"
          branch_name="${branch_name/refs\/heads\//}"
          echo "::set-output name=branch_name::$branch_name"

      - name: Create preliminary release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PERSONAL }}
        with:
          tag_name: ${{ steps.extract_branch_name.outputs.branch_name }}
          release_name: ${{ steps.extract_branch_name.outputs.branch_name }}
          body: Preliminary release based on branch ${{ github.ref }}