name: Preliminary Release

on:
  push:
    branches:
      - 'version/*'
      - 'modules/*'

jobs:
  preliminary_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch_name::${{ github.ref }}"

      - name: Extract branch name
        id: extract_branch_name
        run: |
          branch_name="${{ steps.get_branch_name.outputs.branch_name }}"
          branch_name="${branch_name/refs\/heads\//}"  # Eliminar 'refs/heads/' del principio
          if [[ $branch_name =~ version\/([^\s\/]+) ]]; then  # Si es una rama de versión
            branch_name="v${BASH_REMATCH[1]}"  # Agregar 'v' al principio
          elif [[ $branch_name =~ modules\/([^\s\/]+) ]]; then  # Si es una rama de módulo
            branch_name="${BASH_REMATCH[1]}"  # Mantener el nombre del módulo
          fi
          echo "::set-output name=branch_name::$branch_name"

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_branch_name.outputs.branch_name }}
          name: ${{ steps.extract_branch_name.outputs.branch_name }}
          body: Preliminary release based on branch ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PERSONAL }}