name: Preliminary Release

on:
  push:
    branches:
      - 'version/*'
      - 'modules/*'

jobs:
  preliminary_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch_name::${GITHUB_HEAD_REF}"

      - name: Create preliminary release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ steps.get_branch_name.outputs.branch_name }}
          release_name: ${{ steps.get_branch_name.outputs.branch_name }}
          body: Preliminary release based on branch ${GITHUB_REF}

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./your-artifact.zip
          asset_name: your-artifact.zip
          asset_content_type: application/zip