name: Manual Preliminary Release

on:
  workflow_dispatch:

jobs:
  preliminary_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create preliminary release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: v1.0.0-preliminary
          release_name: v1.0.0 Preliminary
          body: Preliminary release triggered manually

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./your-artifact.zip
          asset_name: your-artifact.zip
          asset_content_type: application/zip