name: Manual Preliminary Release

on:
  workflow_dispatch:

jobs:
  preliminary_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch_name::${{ github.ref }}"

      - name: Extract branch name
        id: extract_branch_name
        run: |
          branch_name="${{ steps.get_branch_name.outputs.branch_name }}"
          branch_name="${branch_name/refs\/heads\//}"  # Eliminar 'refs/heads/' del principio
          if [[ $branch_name =~ version\/([^\s\/]+) ]]; then  # Si es una rama de versión
            branch_name="v${BASH_REMATCH[1]}"  # Agregar 'v' al principio
          elif [[ $branch_name =~ modules\/([^\s\/]+) ]]; then  # Si es una rama de módulo
            branch_name="${BASH_REMATCH[1]}"  # Mantener el nombre del módulo
          fi
          echo "::set-output name=branch_name::$branch_name"

      - name: Build
        run: npm run build

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_branch_name.outputs.branch_name }}
          name: ${{ steps.extract_branch_name.outputs.branch_name }}
          body: Preliminary release based on branch ${{ github.ref }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PERSONAL }}

      - name: Upload release asset
        run: gh release upload ${{ steps.extract_branch_name.outputs.branch_name }} ./dist/* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PERSONAL }}